#!/usr/bin/env bash
# steps involved in installing ngix to running of curl command on the localhost
sudo apt-get -y update
sudo apt-get install nginx -y
sudo ufw allow "Nginx HTPP"
sudo ufw enable
sudo chmod 777 index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx status
sudo service nginx start
# redirecting the web page pamernently if /redirect_me is called
sudo chmod 777 default
new_string=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
               root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files \$uri \$uri/ =404;
        }
        # custom 404 rror page
        error_page 404 /404.html;
        location  /404.html {
            internal;
        }
        
        if (\$request_filename ~ redirect_me){
            rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
        }
}"
sudo chmod 777 /var/www/html/
echo "$new_string" > /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo service nginx restart
